<?xml version="1.0" encoding="utf-8"?><Database Name="LocalDatabase" Class="DatabaseClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\LocalDatabase.mdf;Integrated Security=True" SettingsObjectName="MoneyMaker.Properties.Settings" SettingsPropertyName="LocalDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BankAccount" Member="BankAccount">
    <Type Name="BankAccount">
      <Column Name="BankAccountID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountBalance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="BankAccount_Transactions" Member="Transactions" ThisKey="BankAccountID" OtherKey="BankAccountID" Type="Transactions" />
    </Type>
  </Table>
  <Table Name="dbo.WatchList" Member="WatchList">
    <Type Name="WatchList">
      <Column Name="WatchListID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Depot" Member="Depot">
    <Type Name="Depot">
      <Column Name="DepotID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Settings">
      <Column Name="SettingsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[key]" Member="key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="value" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Stocks" Member="Stocks">
    <Type Name="Stocks">
      <Column Name="StockID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Symbol" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StockExchange" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Typ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Stocks_StocksMap" Member="StocksMap" ThisKey="StockID" OtherKey="StockID" Type="StocksMap" />
    </Type>
  </Table>
  <Table Name="dbo.StocksMap" Member="StocksMap">
    <Type Name="StocksMap">
      <Column Name="StocksMapID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchasePrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="StocksMap_UserLines" Member="UserLines" ThisKey="StocksMapID" OtherKey="StocksMapID" Type="UserLines" />
      <Association Name="Stocks_StocksMap" Member="Stocks" ThisKey="StockID" OtherKey="StockID" Type="Stocks" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transactions">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionType" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="BankAccountID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="BankAccount_Transactions" Member="BankAccount" ThisKey="BankAccountID" OtherKey="BankAccountID" Type="BankAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserLines" Member="UserLines">
    <Type Name="UserLines">
      <Column Name="LineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StocksMapID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PricePoint1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PricePoint2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TimePoint1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TimePoint2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LineColor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Thickness" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="StocksMap_UserLines" Member="StocksMap" ThisKey="StocksMapID" OtherKey="StocksMapID" Type="StocksMap" IsForeignKey="true" />
    </Type>
  </Table>
</Database>